### ISSUE TITLE
HDMI CEC

### ISSUE THREAD

**Issue by tommyMX** [withstu/ioBroker.heos#104]
Hi,

ist es möglich  einen speziellen HDMI Eingang anzusteuern per Befehl?

Ich frage deshalb weil dann dank CEC ja auch der TV mit angeht, was eine gute Lösung wäre..

Da ich diesen sonst nicht anders anbekomme z.b. über Alexa oder ähnliches.

Und Sobald ich den Denon anmache geht automatisch der TV eben auch an.

Wäre dankbar für Eure Hilfe.

VG

**Comment by withstu** [comment]
Hi,

schau mal auf Seite 38 (Play Input source), ob dir das play_input weiterhilft: https://rn.dmglobal.com/euheos/HEOS_CLI_ProtocolSpecification.pdf

Als command könntest du dann folgendes verwenden: play_input&input=inputs/cable_sat

Einfacher ist es aber wahrscheinlich den Denon Adapter zu verwenden (selectInput State). Ich weiß nämlich nicht, ob play_input auch funktioniert, wenn HEOS im Receiver gerade nicht als Soundquelle ausgewählt ist.

Grüße
