### ISSUE TITLE
Start HEOS Music with a music station

### ISSUE THREAD

**Issue by tommyMX** [withstu/ioBroker.heos#139]
Hi,

is it possible to start the HEOS Adapter with my favorite Music Station?

In the HEOS App I can choose it manually e.g. TuneIn and then he is playing it.

But I want to make a blockly over IOBroker where I give him a default input when my wake up routine is starting

Thank you

**Comment by withstu** [comment]
Just read the Readme:
https://github.com/withstu/ioBroker.heos#player-command-state
https://github.com/withstu/ioBroker.heos#presets--playlists
