### ISSUE TITLE
Grouping and ungrouping

### ISSUE THREAD

**Issue by fjosepose** [withstu/ioBroker.heos#208]
**Bug description**  
I have two Heos1, one Heos5 and aDenos X1700(surrond with Heos) that I want to group using the Heos Adapter. I can then eg group the (Heos1+Heos1) then (Heos1+Heos1)+Heos5 and finally (Heos1+Heos1+Heos5) + X1700. The grouping is also reflected in the Heos iOS app.

**To Reproduce** 
I can group in the following order: (Heos1+Heos1) then (Heos1+Heos1)+Heos5 and finally (Heos1+Heos1+Heos5) + X1700. The grouping is also reflected in the Heos iOS app. I then want to remove the X1700 from the group, but it stays in the group. I can see on the app that the X1700 actually jumps ouf the group, but the immidiately back. 
The ioBroker log says: [setLastError] result=fail,text=Processing previous command,command=group/set_group

**Expected behavior**  
When trying to remove the X1700 I would expect it to get out of the group. I can remove the X1700 from the group using the iOS app.

**Versions:**  
 - Adapter version: 10.1
 - Node version: v16.16
 - Operating system: Win10

**Comment by withstu** [comment]
The shown error message indicates, that the HEOS player has some error with grouping the players. It seems for me that each player can only execute one command at a time and in error situation the player responds with the error/status report "Processing previous command". In my opinion it is a result of the buggy HEOS software of the player. For me it always helps to reboot the player receiving the command e.g. the leader or to send group commands not that often in a short period of time. In your case it makes sense to sum up the grouping commands (you can add more than one pid to a group). Another option is to activate the option to reboot players on failure, which reboots the players with errors automatically. It is a hacky solution, however i guess we can't expect Bug fixes from HEOS :-(
