### ISSUE TITLE
Command Befehl funktioniert nicht

### ISSUE THREAD

**Issue by tommyMX** [withstu/ioBroker.heos#234]
Hi,

wenn ich einen Command Befehl eingebe passiert leider nichts am Denon.

z.b.

play_preset&preset=2

Das Logfile im Debug Modus gibt auch nicht viel aus leider:

heos.0 | 2022-10-30 11:41:04.849 | debug | [HEARTBEAT] pong
-- | -- | -- | --
heos.0 | 2022-10-30 11:41:04.848 | debug | parseResponse: {"heos": {"command": "system/heart_beat", "result": "success", "message": ""}}
heos.0 | 2022-10-30 11:41:04.847 | debug | onData: {"heos": {"command": "system/heart_beat", "result": "success", "message": ""}}
heos.0 | 2022-10-30 11:41:04.844 | debug | data sent: heos://system/heart_beat
heos.0 | 2022-10-30 11:41:04.844 | debug | [HEARTBEAT] ping

**Versions:**  
 - Adapter version: 1.10.0
 - JS-Controller version: 4.0.23
 - Node version: 16.18
 - Operating system: Synology Docker

Hier noch ein paar Screenshots:

<img width="1679" alt="Bildschirm­foto 2022-10-30 um 10 45 57" src="https://user-images.githubusercontent.com/36209886/198874550-caa78a7a-7cc6-4a21-a030-1b33e903ea7a.png">
<img width="1659" alt="Bildschirm­foto 2022-10-30 um 10 45 47" src="https://user-images.githubusercontent.com/36209886/198874557-4121b7d6-f242-4083-afe6-7833112463bb.png">
<img width="1342" alt="Bildschirm­foto 2022-10-30 um 10 01 08" src="https://user-images.githubusercontent.com/36209886/198874565-783e2038-3c89-4025-b367-df557b43071d.png">

**Comment by withstu** [comment]
The player command play_preset&preset=2 is working for me. The debug log should show a state change message right after you set the player command state "State change - ID: heos.0.players.<PID>.command" followed by a data sent message "data sent: browse/play_preset?pid=<PID>&preset=2". Are the other player commands working: https://github.com/withstu/ioBroker.heos#player-command-state?

**Comment by tommyMX** [comment]
It looks like that no player commands are working :-(

<img width="1575" alt="Bildschirm­foto 2022-11-05 um 09 10 08" src="https://user-images.githubusercontent.com/36209886/200110426-fe85eec5-69b4-4986-b5ce-d76e97f43ab3.png">
<img width="1618" alt="Bildschirm­foto 2022-11-05 um 09 10 15" src="https://user-images.githubusercontent.com/36209886/200110432-e3ca1863-3e67-45f4-8d78-64ca89138ca3.png">
<img width="1567" alt="Bildschirm­foto 2022-11-05 um 09 11 10" src="https://user-images.githubusercontent.com/36209886/200110434-a480cae4-2d6b-4f46-81a0-836af6f4a380.png">

**Comment by tommyMX** [comment]
is it possible to try something over an http request to test the command or over JS? if something is working there

**Comment by withstu** [comment]
In iobroker you should always set states with ack = false. Then it should work.
