### ISSUE TITLE
run specific tune in radio-station

### ISSUE THREAD

**Issue by DaPeace** [withstu/ioBroker.heos#249]
Thanks for coding that adapter. I want to use that adapter together with an nspanel. I only have some buttons there that i can use and i want directly start a radio station via button hit. At the moment i can switch the receiver on/off and change the volume and i can play the last tuned station but i cant switch the station as i dont know what id/information the denon needs to do that task. It there any chance to use your adapter for that? 
Regards,
DaPeace

**Comment by withstu** [comment]
Yes it is possible. Easiest way is to safe the stations as Favorites in the heos app and set the command state: play_preset&preset=1, play_preset&preset=2 etc.
