### ISSUE TITLE
Queue lässt sich nicht mehr löschen

### ISSUE THREAD

**Issue by Norb1204** [withstu/ioBroker.heos#306]
Hallo,
seit kurzem lässt sich die Queue (clear_queue) nicht mehr löschen.

Gruß
Norbert

**Comment by withstu** [comment]
Ich habe es bei mir gerade ausgetestet und konnte keine Probleme feststellen. Ist das Gerät verbunden?

**Comment by Norb1204** [comment]
Nach ein bisschen rumtesten funktioniert es jetzt.
Nach dem clear_queue command habe ich noch eine Zeit von 5 Sekunden eingebaut bevor der nächste Befehl gesendet wird.
Danke für die Rückmeldung.
