### ISSUE TITLE
Heos Widget VIS2

### ISSUE THREAD

**Issue by ostseereiter1** [withstu/ioBroker.heos#324]
Hello, I have tried to get the Heos widget to work in VIS 02. Unfortunately buttons are not displayed correctly and have no function. Will these be adapted? see also the forum.  [https://forum.iobroker.net/topic/73347/heos-mit-vis-2/2?_=1710258088960](url)

Hallo ich habe versucht das Heos Widget in VIS 02 zum laufen zu bringen. Leider werden Button nicht richtig dargestellt und haben keine Funktion. Werden diese angepasst? siehe auch das Forum. https://forum.iobroker.net/topic/73347/heos-mit-vis-2/2?_=1710258088960](url)

**Comment by withstu** [comment]
Hi, aktuell ist nicht geplant Widgets für Vis 2 zu entwickeln. Sollte aber nicht kompliziert sein für die Favoriten. Als Action des Buttons muss für den ersten Favorit nur folgender State gesteuert werden: heos.0.sources.1028.1.play. Das Image befindet sich im State heos.0.sources.1028.1.image_url.
